modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC0-1.0"

[[mods]]
modId = "foglooksmodernnow"
version = "${version}"
displayName = "Fog Looks Modern Now"
logoFile = "icon.png"
displayURL = "https://github.com/shizotoaster/foglooksmodernnow"
description = '''
Fog Looks Good Now for modern Minecraft versions
'''
authors = '''

    * shizotoaster - Updated FLGN to modern MC versions
'''
credits = '''

    * mineblock11, Hatsuya - Fabric port authors
    * CAPPIN - Original Forge mod author
'''

[[mixins]]
config = "foglooksmodernnow.mixins.json"

[[dependencies.foglooksmodernnow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
